
app:
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
  spring:
    ldap:
      embedded:
        base-dn: dc=springframework,dc=org
        ldif: classpath:test-server.ldif
        port: 8389
        validation:
          enabled: false